# Generated by Django 3.1.1 on 2023-03-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='spaces',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.Space'),
        ),
    ]
