# Generated by Django 3.2.18 on 2023-03-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='users.BadgeTasks'),
        ),
    ]
