# Generated by Django 3.2.18 on 2023-03-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230327_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='task_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
