# Generated by Django 3.2.18 on 2023-03-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230323_1042'),
        ('users', '0011_delete_userbadge'),
    ]

    operations = [
    ]
