# Generated by Django 3.2.18 on 2023-05-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0007_interest'),
        ('users', '0012_badge_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, to='spaces.Interest'),
        ),
    ]
