# Generated by Django 3.2.18 on 2023-03-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20230330_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgetasks',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='badgetasks',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='badges',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='BadgeTasks',
        ),
    ]
