# Generated by Django 3.2.18 on 2023-04-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_badge_userbadge'),
        ('users', '0014_auto_20230330_1310'),
    ]

    operations = [
    ]
