version: "3.8"
services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    image: app:latest
    container_name: swe574_term_project
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=swe574
      - DB_PASSWORD=admin
      - DB_USER=admin
      - SECRET_KEY=developmentSecretKey
      - DEBUG=1
    ports:
      - "80:8000"


volumes:
  postgres_data:
