# Generated by Django 3.2.18 on 2023-04-09 21:44

import annotations.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('context', models.CharField(default='http://www.w3.org/ns/anno.jsonld', max_length=255, validators=[annotations.validators.validate_iri])),
                ('type', models.CharField(default='Annotation', max_length=255, validators=[annotations.validators.validate_annotation_type])),
                ('body', models.CharField(max_length=225, validators=[annotations.validators.validate_iri])),
                ('target', models.CharField(max_length=225, validators=[annotations.validators.validate_iri])),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'annotation',
                'verbose_name_plural': 'annotations',
                'ordering': ['creation_datetime'],
            },
        ),
    ]
