# Generated by Django 3.2.18 on 2023-05-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='body',
            field=models.JSONField(max_length=255),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='target',
            field=models.JSONField(max_length=255),
        ),
    ]
