# Generated by Django 3.2.18 on 2023-03-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230328_0029'),
        ('users', '0007_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_posts', to='posts.Post', verbose_name='Bookmarked Posts'),
        ),
    ]
