# Generated by Django 3.1.1 on 2023-03-16 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0002_auto_20230313_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='space',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_spaces', to=settings.AUTH_USER_MODEL),
        ),
    ]
