# Generated by Django 3.2.18 on 2023-05-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('posts', '0008_auto_20230328_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_description', to='taggit.tag')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag_descriptions',
            field=models.ManyToManyField(blank=True, to='posts.TagDescription'),
        ),
    ]
