# Generated by Django 3.2.18 on 2023-05-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_reportedpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportedpost',
            old_name='reporter',
            new_name='reported_by',
        ),
    ]
