# Generated by Django 3.2.18 on 2023-05-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_usertaginteraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTagInteraction',
        ),
    ]
