name: Coverage Report

on:
    push:
    pull_request:
        branches:
            - production
            - development
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout action
            uses: actions/checkout@v2
          - name: Django Coverage action
            uses: actions/python-django-coverage-github-action@0.9
            with:
              django-app: 'authenticator'
              minimum-coverage: '70'
