name: Coverage Report

on:
    push:
    pull_request:
        branches:
            - production
            - development
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Get Coverage Report
            uses: orgoro/coverage@v3
