name: All

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        services:
          postgres:
            image: postgres:13-alpine
            env:
              POSTGRES_DB: postgres
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
            ports:
            - 5432:5432
            # needed because the postgres container does not provide a healthcheck
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:

        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v3
          with:
            ref: production

        - name: Set up Python 3.8
          uses: actions/setup-python@v3
          with:
            python-version: 3.8

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest-django

        - name: Run migrations
          run: |
            python manage.py migrate

        - name: Run Tests
          run: |
            python manage.py test
