name: Django Tester

on: [push]
env:
  DEBUG: "1"
  SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST: ${{ secrets.DB_HOST }}
  ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello $DB_NAME"
      - run: echo "Hi ${{ secrets.DB_USER }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
      - run: python manage.py test
